//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajSistemiUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KomisyonBilgi
    {
        public string Unvan { get; set; }
        public string AkademisyenAdi { get; set; }
        public string AkademisyenSoyadi { get; set; }
        public string Gorev { get; set; }
    }
}
