//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajSistemiUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MulakatBilgi
    {
        public double OgrenciNo { get; set; }
        public double Devam { get; set; }
        public double CalismaVeCaba { get; set; }
        public double IsVaktindeDavranis { get; set; }
        public double AmireKarsiDavranis { get; set; }
        public double IsArkadaslarinaDavranis { get; set; }
        public double Prove { get; set; }
        public double Duzen { get; set; }
        public double Sunum { get; set; }
        public double Icerik { get; set; }
        public double Mulakat { get; set; }
        public System.DateTime MulakatTarihiVeSaati { get; set; }
        public Nullable<double> MulakatYuzde { get; set; }
    
        public virtual OgrenciBilgi OgrenciBilgi { get; set; }
    }
}
