//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajSistemiUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciBilgi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OgrenciBilgi()
        {
            this.DgsVeYatayBilgi = new HashSet<DgsVeYatayBilgi>();
            this.MulakatBilgi = new HashSet<MulakatBilgi>();
            this.StajBilgi = new HashSet<StajBilgi>();
        }
    
        public double OgrenciNo { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public int Ogretim { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DgsVeYatayBilgi> DgsVeYatayBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MulakatBilgi> MulakatBilgi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StajBilgi> StajBilgi { get; set; }
    }
}
