//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajSistemiUygulamasi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StajBilgi
    {
        public double OgrenciNo { get; set; }
        public int Sinif { get; set; }
        public string KurumAdi { get; set; }
        public string Sehir { get; set; }
        public string StajKonusu { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<int> ToplamGun { get; set; }
        public int KabulEdilenGun { get; set; }
        public bool StajDegerlendirildi { get; set; }
    
        public virtual OgrenciBilgi OgrenciBilgi { get; set; }
    }
}
